# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

# Python Script Generated by Mslice on 2021-06-17 11:36:38
import mslice.cli as mc
import mslice.plotting.pyplot as plt

ws_er2ir2o7_Ei180_5K = mc.Load(Filename='/home/dl11170/edatc/powder_data/er2ir2o7_Ei180_5K.nxspe', OutputWorkspace='er2ir2o7_Ei180_5K')

cut_ws_0 = mc.Cut(ws_er2ir2o7_Ei180_5K, CutAxis="|Q|,2.0,16.0,0.08152", IntegrationAxis="DeltaE,20.0,55.0,0.0", NormToOne=False)
lo_q_cut = mc.Cut(ws_er2ir2o7_Ei180_5K, IntegrationAxis="|Q|,2.0,5.0,0.0", CutAxis="DeltaE,-20,100,1", NormToOne=False)
hi_q_cut = mc.Cut(ws_er2ir2o7_Ei180_5K, IntegrationAxis="|Q|,13.0,16.0,0.0", CutAxis="DeltaE,-20,100,1", NormToOne=False)

low_q = 3.5
high_q = 14.5

xx = cut_ws_0.get_coordinates()
xx = xx[list(xx.keys())[0]]
yy = cut_ws_0.get_signal()
scale = np.interp(low_q, xx, yy) / np.interp(high_q, xx, yy)
print(scale)

mag_cut = lo_q_cut - (scale * hi_q_cut)

# Plots the cuts and the difference

fig = plt.gcf()
ax = fig.add_subplot(111, projection="mslice")
ax.errorbar(lo_q_cut, label="er2ir2o7_Ei180_5K Low Q", color="blue", marker="o", ls="-", lw=1.5, intensity_range=(0.0, 500.0))
ax.errorbar(hi_q_cut, label="er2ir2o7_Ei180_5K High Q", color="green", marker="o", ls="-", lw=1.5, intensity_range=(0.0, 500.0))
ax.errorbar(mag_cut, label="er2ir2o7_Ei180_5K Magnetic", color="red", marker="o", ls="-", lw=1.5, intensity_range=(0.0, 500.0))

ax.set_title('')
ax.set_ylabel(r'Signal/#Events')
ax.set_xlabel(r'Energy Transfer (meV)')
ax.set_ylim(bottom=-50.0, top=150.0)
ax.set_xlim(left=-20, right=100)
mc.Show()
